---

app_user: "ansible"
http_host: "humidity_server" #could be cigarsensors or something like that
http_conf: "humidity_server.conf"
http_port: "80"
ansible_default: true
default_user: "ansible"
default_group: "wheel"
default_password: "hktelemacher"
mysql_username: "ansible"
mysql_password: "hktelemacher"
mysql_root_password: "hktelemacher"
device_name: 'humidity_server'
repository: "pi_humidity_server"
ansible_pi_ip: 192.168.1.11
api_key: "openweathermap_API_here"
zip_code: '43210'
ssh_key: 'ssh-key_here'
sender_email: 'youremail@whatever.com'
receiver_email: 'youremail@whatever.com'
email_password: 'mysupersecretpasswordhere'
...